api_key: 'key-81bc28dea29bbed47d96d0223d7e6632'
domain: 'sandboxa0d55ded1ccb4828b6a5f504079dff81.mailgun.org'
username: 'postmaster@sandboxa0d55ded1ccb4828b6a5f504079dff81.mailgun.org'
password: '0db7ca7e990c643bcb3a29c5b60dd06e'
gmail_username: 'oyr.wishlist@gmail.com'
gmail_password: 'formymoney'